An error has occurred. Please contact system administrator. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object. at earth.CommonFunctions.AzureFunction.FO.DmfManager.import(HttpContent content, String activityId, String company, ILogger log, String zipFileName, Boolean businessErrorFlag) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FO\DMFManager.cs:line 0 at earth.CommonFunctions.AzureFunction.FO.DmfManager.ImportFromStorage(String filePath, String activityId, String company, String container, String fileDir, ILogger log, Boolean businessErrorFlag) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FO\DMFManager.cs:line 136 at earth.CommonFunctions.AzureFunction.FunctionBase.BatchImport(String filePath, String companycode, String container, String activityName, ILogger log, String businessErrorFlag) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FunctionBase.cs:line 507 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at LegacySystem.DemandPlanning.FO.In.Batch.LS_BT_00303.LS_BT_00303_BusinessLogic.BussinessLogic(Object[] inputList) in D:\a\1\s\AzureServices\AzureFuction\LegacySystem\DemandPlanning\FO\In\Batch\LegacySystem.DemandPlanning.FO.In.Batch.LS_BT_00303\LS_BT_00303_BusinessLogic.cs:line 14 at earth.CommonFunctions.AzureFunction.FunctionBase.Run(Object[] inputList) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FunctionBase.cs:line 127
