 InternalServerError executing request 

traces
| project
    timestamp,message,
    operation_Name,
    operation_Id,
    cloud_RoleName,
    invocationId=customDimensions['InvocationId']
| where timestamp >= datetime(2024-10-15T03:00:00Z) and timestamp <= datetime(2024-10-15T04:00:00Z)
| where cloud_RoleName =~ 'earth-stg-func-jpe-ls-dp-fo-in-batch-st2' and operation_Name =~ 'Do_LS_BT_00301_Action'
| order by timestamp desc


traces
| project
    timestamp,
    message,
    operation_Name,
    operation_Id,
    cloud_RoleName,
    invocationId=customDimensions['InvocationId']
| where timestamp >= datetime(2024-10-15T00:00:00Z) and timestamp <= datetime(2024-10-15T23:59:59Z)
| where cloud_RoleName =~ 'earth-stg-func-jpe-ls-dp-fo-in-batch-st2' 
| where operation_Name =~ 'Do_LS_BT_00301_Action'
| where message contains 'error'
| order by timestamp desc


An error has occurred. Please contact system administrator.
System.AggregateException: One or more errors occurred. (DMF Error.DMF data job [3d19826c-6ecb-40c6-9305-8d108246af58]:activityId=[62fc7d21-24ab-4b0b-afc0-2c056603552d]:dmfstatus=ProcessedWithErrors:batchjobstatus=Executing:Zip file name=[st2/importpackage/0302/ad2c43ba-44d4-481b-a8ea-399114d54496.zip])
---> System.Net.Http.HttpRequestException: DMF Error.DMF data job [3d19826c-6ecb-40c6-9305-8d108246af58]:activityId=[62fc7d21-24ab-4b0b-afc0-2c056603552d]:dmfstatus=ProcessedWithErrors:batchjobstatus=Executing:Zip file name=[st2/importpackage/0302/ad2c43ba-44d4-481b-a8ea-399114d54496.zip]
at earth.CommonFunctions.AzureFunction.FO.DmfManager.import(HttpContent content, String activityId, String company, ILogger log, String zipFileName, Boolean businessErrorFlag) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FO\DMFManager.cs:line 696
at earth.CommonFunctions.AzureFunction.FO.DmfManager.ImportFromStorage(String filePath, String activityId, String company, String container, String fileDir, ILogger log, Boolean businessErrorFlag) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FO\DMFManager.cs:line 136
at earth.CommonFunctions.AzureFunction.FunctionBase.BatchImport(String filePath, String companycode, String container, String activityName, ILogger log, String businessErrorFlag) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FunctionBase.cs:line 507
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at LegacySystem.DemandPlanning.FO.In.Batch.LS_BT_00302.LS_BT_00302_BusinessLogic.BussinessLogic(Object[] inputList) in D:\a\1\s\AzureServices\AzureFuction\LegacySystem\DemandPlanning\FO\In\Batch\LegacySystem.DemandPlanning.FO.In.Batch.LS_BT_00302\LS_BT_00302_BusinessLogic.cs:line 14
at earth.CommonFunctions.AzureFunction.FunctionBase.Run(Object[] inputList) in D:\a\1\s\AzureServices\AzureFuction\CommonFunctions\CommonService\FunctionBase.cs:line 127
